spring.application.name=rohith

# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.nmmmggyissdxbugyuycf&password=RohithPortfolio@878
spring.datasource.username=postgres
spring.datasource.password=RohithPortfolio@878
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=10000